// <auto-generated />
using System;
using MakaleApp.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakaleApp.Data.Migrations
{
    [DbContext(typeof(MakaleDbContext))]
    [Migration("20190810093844_start2")]
    partial class start2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MakaleApp.Data.Entity.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(128);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("KategoriAdi");

                    b.Property<DateTime>("UpdateDate");

                    b.Property<string>("UpdatedUserId")
                        .HasMaxLength(128);

                    b.HasKey("KategoriId");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("MakaleApp.Data.Entity.Makale", b =>
                {
                    b.Property<int>("MakaleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Baslik");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(128);

                    b.Property<string>("Icerik");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("KategoriId");

                    b.Property<DateTime>("UpdateDate");

                    b.Property<string>("UpdatedUserId")
                        .HasMaxLength(128);

                    b.HasKey("MakaleId");

                    b.HasIndex("KategoriId");

                    b.ToTable("Makale");
                });

            modelBuilder.Entity("MakaleApp.Data.Entity.Yorum", b =>
                {
                    b.Property<int>("YorumId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(128);

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("MakaleId");

                    b.Property<DateTime>("UpdateDate");

                    b.Property<string>("UpdatedUserId")
                        .HasMaxLength(128);

                    b.Property<string>("YorumIcerik");

                    b.HasKey("YorumId");

                    b.HasIndex("MakaleId");

                    b.ToTable("Yorum");
                });

            modelBuilder.Entity("MakaleApp.Data.Entity.Makale", b =>
                {
                    b.HasOne("MakaleApp.Data.Entity.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MakaleApp.Data.Entity.Yorum", b =>
                {
                    b.HasOne("MakaleApp.Data.Entity.Makale", "Makale")
                        .WithMany()
                        .HasForeignKey("MakaleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
